### PR TITLE
Readying the repository

### PR DESCRIPTION
**Pull request by gwenchee**
This PR addresses https://github.com/arfc/cyder/issues/16 and https://github.com/arfc/cyder/issues/17.

### CODE REVIEW

**Review by katyhuff — APPROVED** [review]
Seems ok to me. Do you think this is ready?

**Comment by gwenchee** [comment]
I think it will be ready after I resolve all the pep8 issues @katyhuff

**Comment by katyhuff** [comment]
How about this: we can merge now, create an issue to resolve the pep8 stuff, and resolve in a separate PR?

**Comment by gwenchee** [comment]
Sure that sounds good! @katyhuff

**Comment by gwenchee** [comment]
I will create the issue @katyhuff

**Pull request merged**
